### ISSUE TITLE
[BUG] array_join array argument not recognised as array

### ISSUE THREAD

**Issue by AlisonSelby** [liana-p/narrat-engine#261]
**Describe the bug**
When using the array_join command as documented, the operation fails with a runtime error that the command "requires an array argument. The args printed in the console show that the array argument is wrapped in a Proxy object.

**To Reproduce**
1. Assign an array `var testingarray (new Array "Test" "ing")`
2. Use the array_join command and log the result  `log (array_join $testingarray "")`

**Expected behavior**
In this example, the expected result is the string "Testing"

**Screenshots**
![image](https://github.com/liana-p/narrat-engine/assets/1810848/41934d16-6e82-46b2-a994-57a15c720a41)

**Browser**
If relevant, which browser/OS is this happening on
Tested on both Firefox 124 and Edge 123

**Comment by liana-p** [comment]
This works fine when I test it locally, I'm not getting any error about the variable not being an array.
```
dev_test:
  var testarray (new Array "Test" "ing")
  log $testarray
  var result (array_join $testarray "")
  log $result
```
![image](https://github.com/liana-p/narrat-engine/assets/32243840/6054712e-6ee8-41b7-a188-b53c34ac381f)

![image](https://github.com/liana-p/narrat-engine/assets/32243840/55bc35b3-0c66-4cac-88e3-d28694128020)

The code of the command is like this:
![image](https://github.com/liana-p/narrat-engine/assets/32243840/f523b745-61cb-404e-bfe0-46e5ee29cadf)

It calls `Array.isArray` to check that the value passed is definitely an array. Might be worth doing a `log $testingarray` to see what you get and why it's doing this... 

On the other hand, I realised the command doesn't return the right thing. It returns the array instead of returning the result of `join`, so I'll change that.
